distr_stats <- function(ii){
  # A simple function to gather a set of statistics to perform on 
  # a sample of (e.g.) intakes.
  # Generated by JOS: 040520
  c('Mean' = mean(ii),
    'std.error' = sd(ii)/sqrt(length(ii)),
    '95% CI for mean lower' = mean(ii)-2*sd(ii)/sqrt(length(ii)),
    '95% CI for mean upper' = mean(ii)+2*sd(ii)/sqrt(length(ii)),
    'mean trimmed 5%' = mean(ii[round(length(ii)*0.025):round(length(ii)*0.975)]),
    'median' = median(ii),
    'variance' = var(ii),
    'std dev'  = sd(ii),
    'minimum'  = min(ii),
    'maximum'  = max(ii),
    'range'    = max(ii)-min(ii),
    'interquartile range' = quantile(ii,0.75) - quantile(ii,0.25),
    'skewness' = mean(((ii-mean(ii))/sd(ii))^3),
    'kurtosis' = mean(((ii-mean(ii))/sd(ii))^4))
  
}
